coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0.5%
        base: auto
        removed_code_behavior: adjust_base
ignore:
  - "**/*.stories.tsx"
  - "**/*.(test|stories).{ts,tsx}"
  - "**/index.ts"
  - "**/store/data/**"
  - "**/stubs/**"
  # Ignore SourceCode editor coverage because it's not possible to test it through Jest (it's a monaco editor)
  - "packages/kaoto-ui/src/components/SourceCode/*.{ts,tsx}"
