coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0.5%
        base: auto
        removed_code_behavior: adjust_base
ignore:
  - "**/*.stories.tsx"
  - "**/*.(test|stories).{ts,tsx}"
  - "**/index.ts"
  - "**/store/data/**"
  - "**/stubs/**"
