nodeLinker: node-modules

# https://yarnpkg.com/configuration/yarnrc#enableScripts
enableScripts: false

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
