packageExtensions:
  react-router-last-location@*:
    dependencies:
      history: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v2"

yarnPath: .yarn/releases/yarn-3.1.0.cjs
