name: '🐛 Bug Report'
description: Create a report to help us improve Kaoto
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue :pray:.

        - This issue tracker is for reporting bugs found in [Kaoto UI](https://github.com/KaotoIO/kaoto-ui)
        - If you have a question about how to achieve something and are struggling, please post a question
        inside of Kaoto's [Discussions](https://github.com/KaotoIO/kaoto-ui/discussions)
        - If it's an issue about the website please go to the [kaoto.io website repo](https://github.com/KaotoIO/kaoto.io)
        - If it's an issue about the backend or API, please go to [that repo](https://github.com/KaotoIO/kaoto-backend)

        Before submitting a new bug/issue, please check the links below to see if there is a solution or question posted there already:
         - [Kaoto's Open Issues](https://github.com/KaotoIO/kaoto-ui/issues?q=is%3Aissue+sort%3Aupdated-desc+position)
         - [Kaoto's Closed Issues](https://github.com/KaotoIO/kaoto-ui/issues?q=is%3Aissue+sort%3Aupdated-desc+position+is%3Aclosed)
         - [Kaoto Discussions](https://github.com/KaotoIO/kaoto-ui/discussions)

        The more information you fill in, the better the community can help you.
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: Provide a clear and concise description of the challenge you are running into.
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Your Example Website or App
      description: |
        Which website or app were you using when the bug happened?
        Note:
        - Your bug will may get fixed much faster if we can run your code and it doesn't have dependencies other than
        Kaoto.
        - To create a shareable code example you can use [Codesandbox](https://codesandbox.io) or [Stackblitz](https://stackblitz.com/).
        - Please read [these tips](https://stackoverflow.com/help/mcve) for providing a minimal example.
      placeholder: |
        e.g. https://stackblitz.com/edit/...... OR Github Repo
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Bug or Issue
      description: Describe the steps we have to take to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or Videos
      description: |
        If applicable, add screenshots or a video to help explain your problem.
        For more information on the supported file image/file types and the file size limits, please refer
        to the [following link](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files).
      placeholder: |
        You can drag your video or image files inside of this editor ↓
  - type: textarea
    id: platform
    attributes:
      label: Platform
      value: |
        - OS: [e.g. macOS, Windows, Linux]
        - Browser: [e.g. Chrome, Safari, Firefox]
        - Version: [e.g. 0.30.0]
    validations:
      required: true
