export default [
  {
    data: {
      label: {
        key: null,
        ref: null,
        props: {
          children: {
            type: 'strong',
            key: null,
            ref: null,
            props: { children: 'twitter-search-source' },
            _owner: null,
            _store: {},
          },
        },
        _owner: null,
        _store: {},
      },
    },
    id: '0twitter-search-source',
    position: { x: 250, y: 0 },
    style: { background: '#D6D5E6', color: '#333', border: '1px solid #222138', width: 180 },
    type: 'input',
  },
  { data: { label: 'pdf-action' }, id: '1pdf-action', position: { x: 0, y: 100 } },
  { data: { label: 'caffeine-action' }, id: '2caffeine-action', position: { x: 0, y: 200 } },
  { data: { label: 'kafka-sink' }, id: '3kafka-sink', position: { x: 0, y: 300 }, type: 'output' },
  {
    id: 'e0twitter-search-source-1pdf-action',
    arrowHeadType: 'arrowclosed',
    source: '0twitter-search-source',
    target: '1pdf-action',
    label: 'cheese',
    labelBgPadding: [8, 4],
    labelBgBorderRadius: 4,
    labelBgStyle: { fill: '#FFCC00', color: '#fff', fillOpacity: 0.7 },
  },
  {
    id: 'e1pdf-action-2caffeine-action',
    arrowHeadType: 'arrowclosed',
    source: '1pdf-action',
    target: '2caffeine-action',
    label: 'cheese',
    labelBgPadding: [8, 4],
    labelBgBorderRadius: 4,
    labelBgStyle: { fill: '#FFCC00', color: '#fff', fillOpacity: 0.7 },
  },
  {
    id: 'e2caffeine-action-3kafka-sink',
    arrowHeadType: 'arrowclosed',
    source: '2caffeine-action',
    target: '3kafka-sink',
    animated: true,
    style: { stroke: 'red' },
  },
];
