name:  📦 Build npm Package
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kaoto'
      - run: yarn
      - run: yarn workspace @kaoto/kaoto-ui run build
      - run: yarn workspace @kaoto/kaoto-ui run build:lib
