# .github/workflows/chromatic.yml

# Workflow name
name: 📖 Storybook (via Chromatic)

# Event for the workflow
on: push

# List of jobs
jobs:
  chromatic-deployment:
    if: github.actor != 'renovate[bot]'
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v3
        with:
          # 👇 Fetches all Git history so that Chromatic can compare against the previous version
          fetch-depth: 0
      - name: Install dependencies
        # 👇 Install dependencies with the same package manager used in the project (replace it as needed), e.g. yarn, npm, pnpm
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: 14f589a59855
          buildScriptName: build:storybook
